# -*- coding: utf-8 -*-
"""streamlit_cloud_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-gp5rTiKHhSNg0il-tdg9Czo6sqN0pi
"""

import streamlit as st
import pandas as pd
import numpy as np
st.write('Hello, *World!* :sunglasses:') # 해당 내용을 수정해서 사이트를 자유롭게 꾸밀 수 있다.
st.write("테스트 입니다.")
input = st.text_input("message")
st.write(input) 

# 제목
st.title('Streamlit 예제')

# 데이터 생성
data = pd.DataFrame({
    'number': range(1, 11),
    'square': [x ** 2 for x in range(1, 11)],
})

# 데이터 표시
st.write("간단한 데이터 테이블")
st.write(data)

# 차트 그리기
st.line_chart(data)