# -*- coding: utf-8 -*-
"""streamlit_cloud_bigdata2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E7fsPezSpTx4l68FrDKz_Qhnf42_bA9j
"""

def run_streamlit_app2():
    import pandas as pd
    import streamlit as st


    # GitHub 또는 GitLab에서 CSV 파일 로드
    data_url = 'https://github.com/nsg716/test_streamlit_cloud/blob/master/test.csv'
    data = pd.read_csv(data_url)
    st.write(data)



